opentesting:
  appname: opentesting
  poolsize: 50
  checkcron: [ "0 * * * * ?", "10 * * * * ?", "20 * * * * ?", "30 * * * * ?", "40 * * * * ?", "50 * * * * ?"]
  longrunningwarn: 5
  downloadmaxchecks: 1000
  resttimeout: 30
  reloadtestcases: true
  autodelete: 7
  salt: 3Z2NQEGUeLhHQptErfrVqu973DfRsQYstz3VppXXWgWAdKfxRNVjutsDbEFvJGfHjK5UPkfjJXvj2SPPqSYK4m2zQw5zpG92ZG3czC4u9Gk8ztu2kSw2XJZDyejr7Asm9TB7J7eYyHYmhFZmDwK2v2K6WqMC68qsW27jw4Pn672WnXJxpKzPhhRZQUDWyKH5j97efvKMQwwrQxB532chZJeAGFb5TddMJVWX2JpRhjbe6byjcPPHbPxqsTjxhbbjQAggAQED5nbZmM9V5SkebH3t8NFjZCQnFNJC6JR89fAP7bawN2sMKuF33RLcNcyVQqFVPA3GwXzuKdEhWFdmP3cPjGawLQjhECP5fKWBKaEXyyDDEUYMe2gUMXSm8vPgKWRCfa2dZabrcEXA4QSzKLgexQY7SZ6e4JjFeWVZdNVQwnURxrZgED6fHhDZg4pcj7TyBvwMud4d4E6rscePMvBfYSRKNMurNuKxMDwN83bUkV6q7AZyPEmggTFZEtzEWvBRYMpqxBttb56kBZKtu7GvnHQ7w5FvXPVWhyvUSCDyG5UCr75d76ABWdxZ2aAJ4S4DM4jmGHdvJXVfvgZYZWfNmWShMZ46KvB6TZwku2FcZy6AqV2DN8Fys5RgdyBBez4vEzQJZPzwbkzHWaN9G3Ye768cqy3xX3GgNbgt7VYmFaKRNRMaH9gTTLDH7Kp37sXLfCaA2WW5huaeWQRbbXf8Aye4yG2DzdSEdMG8MdVpNZFkZUy4kzrHnuWrzUVLsRukrnVA8WpReAYJKsj2ukw3ST6MNwwrkFACqNbR8Fgzu6hZFDpHDazuXMpsBKynjVCdvdg8Kp7R7kYMUv6FBbk5VpdBAChGh7jsS8qnA8PPzRLB4HdQyJrZ57ftwvSf5MMsH4QcyWAyA6uNMnbWe4Ug965nkUnUFbb4eAxnYnLJ9eHYzAhN5Jxx7WzaYPLL77zvz7S69E7kuSZ5u7c7W9MLGXpD86K2RdKr842yGCB7FZ4aSz7v982a89N2PmjnP7YCft3n7jXdmuUFLPmRx92VzcLrcjKVSUN9G535WNuznngQu8tBTGmXZHDMs8q7endCWakKE5sDCDda6JqvZVX8NCtepsee2aqg4sEVadNJAQACjzNMAqwdJm7KhG4bB3CRMZk4nADuAsmggw3bvQ2FZfbGa5S2wYFgbKLjyLwnHEUchKBzQH6TwyRgUtnCYapyzjRaF6nTEZpA342PMYwcFmv7F6YaZy8yrUaCvZsCvjLft8dCQcpYqtKWU86RQWNTRq8wc4jCdFWaAHcPrYjEgKzH4Yh7SDyzAj2EaSb5Tc698nvyGn4gyvPKMN9A6SRzwCEB7ADFLKgL7x6ZUpMTH2QnVVwGwYYATP4DmQkUmNhyHSxngjMKhqPPfPtMZXFjfTmxwh43NLakpdeRKpwUWTYbs8Ej7jPZXVGqnMAPbQcQgfFhcXduBhXSpzHYa9MEM2mS9eMVpqbVQWbWRxtJFPtVuY3scxBw4jJrpDEzVyLabxvCu2KQVFferperYBtpzyFAZfNkWR3FahVMJysDqXwkD2LuKvUrMByaebqUdfVwFnEXUe9SGpVth662mN2HrgbaXyBLQdSshLDuZcGjZN7yCqwMLgctQtkuX3DuXBcDB3TGAvWsTJtPQ83HDpsV7pBEEMHHeYbjwEs3dyv9ygCmSk4v5c9NR6eUkqxxN5s6MERYa2jaKdC5BgCFc9EjGabegYtjg64agX9QShpUbPD59ehueCJZfEFVRmnADTNKEtq5t9JUj546Nw27pBzdtFL8tGcFakJJspucy2VjwsUXydhMyPNYXy5SZdSfSnfvtK3bykCXawmLqx59unQks4YHbUA6vK7af5Q5Pa2v33dCDWuxwuCQHZvgaNDhABHZ6ahJXQQfaWjjZdm3DWTL4TRRqT5XYPNMxBjZAZad3A8j6DxbR7yNqTazQZuBeagyNrrtxpDgtGk2DmRvPtNBkUGs3HhHH8xeLR8GYGuabHhuZEhJCudCja9MnykGm7VxLnAGHVY644kfsd6G
  uselock: true

kafka:
  reconnect:
    backoff:
      max:
        ms: 60000
      ms: 1000

app:
  version: ^project.version^
  name: ^project.name^

#kafka:
#  trace:
#    headertraceid: traceId
#    headerspanid: spanId
#    headerparentspanid: parentSpanId
#    headersampled: sampled

server:
  port: 50000
  servlet:
    context-path: /
  shutdown: graceful

spring:
  application:
    name: opentesting  
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password    
    url: jdbc:h2:file:/tmp/testcasedb;DB_CLOSE_ON_EXIT=FALSE;mode=PostgreSQL
    #driver-class-name: org.postgresql.Driver
    #username: postgres
    #password: CTYgzqP9uF8BfA9X
    #url: jdbc:postgresql://172.17.0.1:5432/postgres
  lifecycle:
    #some docker orchestrators use 10 sec as default to kill containers
    timeout-per-shutdown-phase: 5s
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sleuth:
    async:
      enabled: false
    sampler:
      percentage: 0.0
  zipkin:
    service:
      name: opentesting

springdoc:
  swagger-ui:
    operationsSorter: alpha
    path: /swagger-ui/api-docs.html
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health, info, logfile, metrics, prometheus

logging:
  file:
    name: tmp/opentesting.log
